name: EXTREMIS
favicon: null
layout_spectrum: 0.33283418882638216
typography_spectrum: 0.7455126913264394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5897548384964466
  lightness: 0.7497664471156895
  saturation: 0.45324828871525824
  rhythmicContrast: 0.39276638929732144
purpose: []
