typography_spectrum: 0.65933
color:
  brandColors:
    - '#fefefe'
    - '#252326'
    - '#78736d'
    - '#4bb7e6'
    - '#e95a52'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-76713926-4
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a132f0c2-2389-477a-b4b7-269b3fa098ac.png
name: '#ifihadglass'
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfccda81-9277-4173-9aa6-7ae58b96d967.png
title: 'Adventures #throughglass'
description: 'Adventures #throughglass'
purpose: []
