analytics:
  google: UA-60183671-2
color:
  brandColors:
    - '#0064ee'
    - '#6c9ad2'
    - '#122037'
    - '#ffffff'
    - '#c8d2dc'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0
  saturation: 1
cta: {}
layout_spectrum: 1
name: '#throughglass'
opengraph: {}
purpose: []
typography_spectrum: 0.65933
