analytics:
  google: UA-60183671-2
color:
  brandColors:
    - '#0064ee'
    - '#6c9ad2'
    - '#122037'
    - '#ffffff'
    - '#c8d2dc'
  brandStrength: 0.1875
  lightness: 0
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 1
name: EXTREMIS
opengraph: {}
purpose: []
typography_spectrum: 0.65933
