analytics:
  google: UA-60183671-2
color:
  brandColors:
    - '#B0B8C0'
    - '#408098'
    - '#888080'
    - '#F85028'
    - '#50A8D0'
  brandStrength: 0.66694
  lightness: 1
  rhythmicContrast: 0
  saturation: 1
cta: {}
layout_spectrum: 1
name: '#ifihadglass'
opengraph: {}
purpose: []
typography_spectrum: 0.65933
