name: EXTREMIS
favicon: null
layout_spectrum: 0.74566
typography_spectrum: 0.65933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-60183671-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0064ee'
    - '#6c9ad2'
    - '#122037'
    - '#ffffff'
    - '#c8d2dc'
  brandStrength: 0.1875
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
