name: EXTREMIS
favicon: null
layout_spectrum: 0.24383
typography_spectrum: 0.65933
title: EXTREMIS by Steven Mautone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0064ee'
    - '#6c9ad2'
    - '#122037'
    - '#ffffff'
    - '#c8d2dc'
  brandStrength: 1
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
